### PR TITLE
onboarding slider [stage-1]

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@alex-deaconu @ezequielc could you review. thanks!

### CODE REVIEW

**Comment by ezequielc** [comment]
@ghislaineguerin :+1:

**Comment by alex-deaconu** [comment]
@ezequielc are we going to allow the inline script and the `$(document).ready` in a partial? Thanks.

**Comment by ghislaineguerin** [comment]
@alex-deaconu where should I move that too?

**Comment by ezequielc** [comment]
@alex-deaconu As it is an experiment, and the code would be reworked I wasn't strict. But I agree, if it won't be too complicated, we should make it better.

**Comment by ezequielc** [comment]
@ghislaineguerin maybe you can use https://github.com/jonahbron/angular-owl-carousel.

**Comment by alex-deaconu** [comment]
@ezequielc @ghislaineguerin Thanks for looking into this. I'm wondering what the best course of action is here. Maybe we need to have a development step for this experiment? Thoughts? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu @ghislaineguerin  Yes, I think it will be much faster if we do that. Cheers

**Comment by ghislaineguerin** [comment]
@alex-deaconu @ezequielc I'll move the card to the sprint backlog?

**Comment by ghislaineguerin** [comment]
@alex-deaconu @ezequielc can you review this please? thanks!

**Comment by ezequielc** [comment]
@ghislaineguerin Looks good. :+1: Cheers

**Pull request merged**
